import {
  FileText,
  FileSpreadsheet,
  Presentation,
  Image as ImageIcon,
  Combine,
  Scissors,
  Minimize2,
  RotateCw,
  ListOrdered,
  Stamp,
  Lock,
  LockOpen,
  PenSquare,
  FileOutput,
  Hash,
  FileMinus,
  Tags,
  Crop,
  Wrench,
  Code2,
  ScanText,
  FileType2,
  FileCode2,
  ScanLine,
  Pen,
  FileCheck2,
  EyeOff,
  GitCompare,
  RefreshCw,
  Video,
  Clapperboard,
  Film,
  FileAudio,
  Crop as CropIcon,
  AudioLines,
  Gauge,
  Stamp as StampIcon,
} from "lucide-react";

export const TOOL_GROUPS = [
{
  id: "convert",
  label: "Konversi",
  blurb: "Ubah antar format tanpa kehilangan tampilan aslinya.",
  color: "#6366F1",
  colorBg: "color-mix(in srgb, #6366F1 14%, transparent)",
  tools: [
    "word-to-pdf",
    "pdf-to-word",
    "excel-to-pdf",
    "ppt-to-pdf",
    "image-to-pdf",
    "pdf-to-image",
    "convert-image",
    "html-to-pdf",
  ],
},
  {
    id: "organize",
    label: "Atur Halaman",
    blurb: "Gabung, pisah, dan susun ulang halaman sesukamu.",
    color: "var(--coral)",
    colorBg: "var(--coral-bg)",
    tools: [
      "merge-pdf",
      "split-pdf",
      "reorder-pdf",
      "rotate-pdf",
      "manage-pages",
      "crop-pdf",
      "scan-to-pdf",
    ],
  },
  {
    id: "optimize",
    label: "Optimasi & Keamanan",
    blurb: "Perkecil ukuran file dan jaga dokumen tetap aman.",
    color: "var(--success)",
    colorBg: "var(--success-bg)",
    tools: [
      "compress-pdf",
      "watermark-pdf",
      "protect-pdf",
      "unlock-pdf",
      "page-numbers",
      "edit-metadata",
      "sign-pdf",
      "redact-pdf",
      "compare-pdf",
    ],
  },
  {
    id: "edit",
    label: "Edit & Perbaikan",
    blurb: "Sunting isi dan perbaiki dokumen yang bermasalah.",
    color: "var(--sun)",
    colorBg: "var(--sun-bg)",
    tools: ["pdf-editor", "repair-pdf", "ocr-pdf", "pdf-to-txt", "fill-form"],
  },
{
  id: "intelligence",
  label: "PDF Intelligence",
  blurb: "Pahami isi dokumen lebih cepat.",
  color: "#06B6D4",
  colorBg: "color-mix(in srgb, #06B6D4 14%, transparent)",
  tools: ["pdf-to-markdown"],
},
{
  id: "video",
  label: "Video",
  blurb: "Kompres dan edit video langsung di browser, tanpa upload.",
  color: "#EC4899",
  colorBg: "color-mix(in srgb, #EC4899 14%, transparent)",
  tools: [
    "compress-video",
    "edit-video",
    "crop-video",
    "video-speed",
    "watermark-video",
    "video-to-gif",
    "extract-audio",
    "compress-audio",
  ],
},
];

/** Look up a tool's group so UI can render it with that group's playful accent color. */
export function groupOfTool(toolId) {
  return TOOL_GROUPS.find((g) => g.tools.includes(toolId));
}

export const TOOLS = {
  "word-to-pdf": {
    id: "word-to-pdf",
    name: "Word ke PDF",
    short: "Word → PDF",
    description: "Ubah dokumen .docx menjadi PDF siap bagi.",
    icon: FileText,
    accept: ".docx",
    accentTag: "DOCX",
  },
  "pdf-to-word": {
    id: "pdf-to-word",
    name: "PDF ke Word",
    short: "PDF → Word",
    description: "Ekstrak isi PDF menjadi dokumen .docx yang bisa diedit.",
    icon: FileOutput,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "excel-to-pdf": {
    id: "excel-to-pdf",
    name: "Excel ke PDF",
    short: "Excel → PDF",
    description: "Ubah spreadsheet .xlsx menjadi PDF rapi per halaman.",
    icon: FileSpreadsheet,
    accept: ".xlsx,.xls,.csv",
    accentTag: "XLSX",
  },
  "ppt-to-pdf": {
    id: "ppt-to-pdf",
    name: "PowerPoint ke PDF",
    short: "PPT → PDF",
    description: "Ubah slide .pptx menjadi PDF untuk dibagikan.",
    icon: Presentation,
    accept: ".pptx",
    accentTag: "PPTX",
  },
  "image-to-pdf": {
    id: "image-to-pdf",
    name: "JPG/PNG ke PDF",
    short: "Gambar → PDF",
    description: "Gabungkan beberapa gambar menjadi satu file PDF.",
    icon: ImageIcon,
    accept: ".jpg,.jpeg,.png",
    accentTag: "IMG",
  },
  "pdf-to-image": {
    id: "pdf-to-image",
    name: "PDF ke JPG/PNG",
    short: "PDF → Gambar",
    description: "Ekspor setiap halaman PDF sebagai gambar.",
    icon: ImageIcon,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "convert-image": {
    id: "convert-image",
    name: "Konversi Gambar",
    short: "JPG/PNG/WEBP",
    description: "Ubah format gambar antar JPG, PNG, dan WEBP dalam sekejap.",
    icon: RefreshCw,
    accept: ".jpg,.jpeg,.png,.webp",
    accentTag: "IMG",
  },
  "html-to-pdf": {
    id: "html-to-pdf",
    name: "HTML ke PDF",
    short: "HTML → PDF",
    description: "Tulis atau tempel HTML dan ubah menjadi dokumen PDF.",
    icon: Code2,
    accept: null,
    accentTag: "HTML",
  },
  "merge-pdf": {
    id: "merge-pdf",
    name: "Gabung PDF",
    short: "Merge PDF",
    description: "Satukan beberapa file PDF menjadi satu dokumen.",
    icon: Combine,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "split-pdf": {
    id: "split-pdf",
    name: "Pisah PDF",
    short: "Split PDF",
    description: "Pisahkan halaman PDF menjadi file-file terpisah.",
    icon: Scissors,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "reorder-pdf": {
    id: "reorder-pdf",
    name: "Urutkan Halaman",
    short: "Reorder Pages",
    description: "Susun ulang urutan halaman dengan drag & drop.",
    icon: ListOrdered,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "rotate-pdf": {
    id: "rotate-pdf",
    name: "Putar PDF",
    short: "Rotate PDF",
    description: "Putar orientasi satu atau semua halaman.",
    icon: RotateCw,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "compress-pdf": {
    id: "compress-pdf",
    name: "Kompres PDF",
    short: "Compress PDF",
    description: "Perkecil ukuran file PDF untuk dikirim lebih cepat.",
    icon: Minimize2,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "watermark-pdf": {
    id: "watermark-pdf",
    name: "Watermark PDF",
    short: "Watermark",
    description: "Tambahkan teks watermark di setiap halaman.",
    icon: Stamp,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "protect-pdf": {
    id: "protect-pdf",
    name: "Lindungi PDF",
    short: "Protect PDF",
    description: "Kunci PDF dengan kata sandi agar tidak sembarang dibuka.",
    icon: Lock,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "pdf-editor": {
    id: "pdf-editor",
    name: "Editor PDF",
    short: "PDF Editor",
    description: "Edit teks, gambar, tanda tangan, dan anotasi langsung di browser.",
    icon: PenSquare,
    accept: ".pdf",
    accentTag: "PDF",
    isEditor: true,
  },
  "unlock-pdf": {
    id: "unlock-pdf",
    name: "Buka Kunci PDF",
    short: "Unlock PDF",
    description: "Hapus kata sandi dari PDF yang terkunci (perlu kata sandinya).",
    icon: LockOpen,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "page-numbers": {
    id: "page-numbers",
    name: "Nomor Halaman",
    short: "Page Numbers",
    description: "Tambahkan nomor halaman dan teks header pada setiap halaman.",
    icon: Hash,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "manage-pages": {
    id: "manage-pages",
    name: "Hapus / Ekstrak Halaman",
    short: "Hapus/Ekstrak Halaman",
    description: "Pilih halaman untuk dihapus dari dokumen, atau diekstrak jadi PDF baru.",
    icon: FileMinus,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "edit-metadata": {
    id: "edit-metadata",
    name: "Edit Metadata PDF",
    short: "Edit Metadata",
    description: "Ubah judul, penulis, subjek, dan kata kunci dokumen PDF.",
    icon: Tags,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "crop-pdf": {
    id: "crop-pdf",
    name: "Potong Halaman PDF",
    short: "Crop PDF",
    description: "Potong margin/tepi halaman PDF dengan pratinjau langsung.",
    icon: Crop,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "repair-pdf": {
    id: "repair-pdf",
    name: "Perbaiki PDF Rusak",
    short: "Repair PDF",
    description: "Bangun ulang struktur PDF yang rusak/gagal dibuka agar bisa dipakai lagi.",
    icon: Wrench,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "ocr-pdf": {
    id: "ocr-pdf",
    name: "OCR PDF",
    short: "OCR PDF",
    description: "Ubah PDF/gambar hasil pindaian menjadi PDF yang bisa dicari & diseleksi teksnya.",
    icon: ScanText,
    accept: ".pdf,.jpg,.jpeg,.png",
    accentTag: "OCR",
  },
  "pdf-to-txt": {
    id: "pdf-to-txt",
    name: "PDF ke TXT",
    short: "PDF → TXT",
    description: "Ekstrak seluruh teks dari PDF menjadi file .txt polos.",
    icon: FileType2,
    accept: ".pdf",
    accentTag: "TXT",
  },
  "pdf-to-markdown": {
    id: "pdf-to-markdown",
    name: "PDF ke Markdown",
    short: "PDF → Markdown",
    description: "Ubah isi PDF menjadi Markdown, lengkap dengan judul & daftar.",
    icon: FileCode2,
    accept: ".pdf",
    accentTag: "MD",
  },
  "scan-to-pdf": {
    id: "scan-to-pdf",
    name: "Pindai ke PDF",
    short: "Pindai → PDF",
    description: "Foto dokumen dengan kamera atau galeri, langsung jadi PDF rapi.",
    icon: ScanLine,
    accept: "image/*",
    accentTag: "SCAN",
  },
  "sign-pdf": {
    id: "sign-pdf",
    name: "Tanda Tangani PDF",
    short: "Sign PDF",
    description: "Gambar tanda tangan dan tempatkan langsung di halaman PDF.",
    icon: Pen,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "fill-form": {
    id: "fill-form",
    name: "Formulir PDF",
    short: "Isi Formulir",
    description: "Deteksi kolom formulir PDF dan isi langsung dari browser.",
    icon: FileCheck2,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "redact-pdf": {
    id: "redact-pdf",
    name: "Samarkan PDF",
    short: "Redact PDF",
    description: "Hitamkan & hapus permanen bagian sensitif dari halaman PDF.",
    icon: EyeOff,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "compare-pdf": {
    id: "compare-pdf",
    name: "Bandingkan PDF",
    short: "Compare PDF",
    description: "Lihat perbedaan teks antar dua versi PDF, per halaman.",
    icon: GitCompare,
    accept: ".pdf",
    accentTag: "PDF",
  },
  "compress-video": {
    id: "compress-video",
    name: "Kompres Video",
    short: "Compress Video",
    description: "Perkecil ukuran file video (MP4/MOV/WEBM/MKV) langsung dari browser.",
    icon: Video,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "VIDEO",
  },
  "edit-video": {
    id: "edit-video",
    name: "Edit Video",
    short: "Edit Video",
    description: "Potong durasi, putar orientasi, dan bisukan audio video.",
    icon: Clapperboard,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "VIDEO",
  },
  "crop-video": {
    id: "crop-video",
    name: "Crop Video",
    short: "Crop Video",
    description: "Potong area video (bukan cuma rotate) dengan margin atas/bawah/kiri/kanan.",
    icon: CropIcon,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "VIDEO",
  },
  "video-speed": {
    id: "video-speed",
    name: "Ubah Kecepatan Video",
    short: "Speed Video",
    description: "Percepat atau perlambat video (slow motion), audio ikut menyesuaikan.",
    icon: Gauge,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "VIDEO",
  },
  "watermark-video": {
    id: "watermark-video",
    name: "Watermark Video",
    short: "Watermark Video",
    description: "Tambahkan teks watermark ke video — diagonal, tengah, atau berulang.",
    icon: StampIcon,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "VIDEO",
  },
  "video-to-gif": {
    id: "video-to-gif",
    name: "Video ke GIF",
    short: "Video → GIF",
    description: "Ubah potongan video menjadi GIF animasi berkualitas tinggi.",
    icon: Film,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "GIF",
  },
  "extract-audio": {
    id: "extract-audio",
    name: "Ekstrak Audio",
    short: "Video → Audio",
    description: "Ambil trek audio saja dari video, simpan sebagai MP3 atau AAC.",
    icon: FileAudio,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "AUDIO",
  },
  "compress-audio": {
    id: "compress-audio",
    name: "Kompres Audio Video",
    short: "Kompres Audio",
    description: "Turunkan bitrate audio saja tanpa re-encode video — cepat, ukuran lebih kecil.",
    icon: AudioLines,
    accept: ".mp4,.mov,.webm,.mkv,.m4v",
    accentTag: "AUDIO",
  },
};

export const TOOL_LIST = Object.values(TOOLS);
